name = "ThreadProgress"
uuid = "7235a734-d916-4811-a770-8b82c6ae1075"
authors = ["Tomas Fiers <tomas.fiers@gmail.com>"]
version = "0.1.0"

[deps]
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
