# Book settings
title: Voltage-to-Wiring Sim
author: Tomas Fiers
repository:
  url: https://github.com/tfiers/voltage-to-wiring-sim
  path_to_book: notebooks
execute:
  execute_notebooks: off
launch_buttons:
  binderhub_url: https://notebooks.gesis.org/binder
html:
  favicon: _static/favicon.ico
  home_page_in_navbar: true
  baseurl: https://tfiers.github.io/voltage-to-wiring-sim
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true
  extra_navbar: |
    <div id="build-status">
      [build status]
    </div>
  extra_footer: |
    <script src="https://hypothes.is/embed.js" async></script>
