# This file is machine-generated - editing it directly is not advised

julia_version = "1.9.0-beta3"
manifest_format = "2.0"
project_hash = "9e0dfc40d900458e8390d53fd0fa8617fcca5713"

[[deps.GlobalMacros]]
path = "../GlobalMacros"
uuid = "4356e881-4961-4a42-bf31-d836fc29b3e6"
version = "0.1.0"
