
# Container for the data generated by a neural network simulation.
# See `init_sim` for the actual properties inside.
#
# We use this type instead of using the wrapped NamedTuple directly, so that we don't get
# the huge NamedTuple type signatures in stacktraces, and to use it for typing function
# arguments
struct SimData
    data::NamedTuple
end

function Base.getproperty(s::SimData, name::Symbol)
    if name == :data
        getfield(s, :data)  # Avoid recursion
    else
        getproperty(s.data, name)
    end
end

Base.propertynames(s::SimData) = propertynames(s.data)  # For autocompletion in Jupyter.
