# Run the full test suite (in `tests/`) on every push of Python code 
# to GitHub, on a range of Python versions and OS'es.

name: CI

# Avoid markdown or notebook edits triggering the testing machine.
on:
  push:
    paths-ignore: [ '**.ipynb', '**.md' ]

jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]  # 3.9 errors on llvm install

    runs-on: ${{ matrix.os }}

    steps:
      - name: Download repo at latest commit
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update package installer
        run: python -m pip install --upgrade pip

      - name: Install our package
        run: pip install .
      
      - name: Install test runner
        run: pip install pytest

      - name: Run tests
        working-directory: codebase/tests
        run: pytest
