name: deploy-website

# Only run when anything in the `website` or `notebooks` directories changes
on:
  push:
    paths:
      - notebooks/**
      - website/**

# Install dependencies, build the book, and push it to `gh-pages` branch.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Restore cached pip downloads
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('website/requirements.txt') }}

    - name: pip install -r website/requirements.txt
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r website/requirements.txt

    - name: Build the book
      working-directory: website
      run: python build.py

    - name: Push the book's HTML to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: website/_build/html
